export const OBTENER_USUARIOS = 'OBTENER_USUARIOS'
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const USUARIO_ACTUAL = 'USUARIO_ACTUAL';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const POST_ERROR = 'POST_ERROR';


